version: "3.9"

services:

  db:
    image: mysql:5.7
    container_name: $DB_CONTAINER
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "$PORT_MYSQL:3306"
    env_file:
      - .env
    restart: always
    volumes:
      - kpworkout_mysql_data:/var/lib/mysql

  frontend-react:
    build:
      context: ./frontend
    container_name: frontend_react
    working_dir: /app
    ports:
      - "$PORT_REACT:5173"
    env_file: .env
    volumes:
      - ./frontend:/app
    
  backend-laravel:
    build: 
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: $LARAVEL_CONTAINER
    env_file:
      - .env
    command: sh -c './wait-for-it.sh $DB_CONTAINER 3306 $MYSQL_DATABASE; ./migrate.sh; php artisan serve --host=0.0.0.0 --port=8000'
    ports:
      - "$PORT_LARAVEL:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - kpworkout_laravel_uploads:/app/public/uploads
      - ./backend/migrate.sh:/app/migrate.sh
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: $PHPMYADMIN_CONTAINER
    restart: always
    environment:
      PMA_HOST: $DB_CONTAINER
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "8080:80"

volumes:
  kpworkout_mysql_data:
  kpworkout_laravel_uploads: